-- =====================================================================
-- HILMY · mig 69 — rate-limit du hand-off auth mobile→web
--
-- Support du rate-limit de l'Edge Function `web-login-link` (hand-off
-- magic-link mobile→web pour le paiement B2B). Revue hilmy-security
-- 2026-06-16 (condition 🟠) : 5/min + 20/h par user.id.
--
-- Additif et idempotent : nouvelle table + nouvelle fonction. AUCUNE
-- table ni donnée existante n'est touchée. Aucun impact RLS sur
-- l'existant.
-- =====================================================================

-- Table d'attempts (interne, alimentée uniquement via la RPC ci-dessous).
create table if not exists public.web_login_link_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists web_login_link_attempts_user_time_idx
  on public.web_login_link_attempts (user_id, created_at desc);

-- RLS activée SANS policy = deny par défaut pour anon/authenticated.
-- Seuls la RPC (SECURITY DEFINER) et le service_role (bypass) y touchent.
alter table public.web_login_link_attempts enable row level security;

-- RPC atomique : sérialise par user (advisory lock), purge l'historique
-- > 1h, compte les fenêtres 1min / 1h, insère si sous les caps, renvoie
-- true (autorisé) / false (throttlé). SECURITY DEFINER + search_path figé.
create or replace function public.web_login_link_allow(p_user_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_last_min  int;
  v_last_hour int;
begin
  -- Sérialise les appels concurrents du MÊME user (anti-race TOCTOU).
  -- Lock namespacé (classe = feature, objet = user) → zéro contention
  -- avec d'autres advisory locks dérivés du même user_id (revue sécu R1).
  perform pg_advisory_xact_lock(hashtext('web_login_link_allow'), hashtext(p_user_id::text));

  -- Housekeeping : ne garder que la dernière heure pour ce user.
  delete from public.web_login_link_attempts
  where user_id = p_user_id
    and created_at < now() - interval '1 hour';

  select
    count(*) filter (where created_at >= now() - interval '1 minute'),
    count(*) filter (where created_at >= now() - interval '1 hour')
  into v_last_min, v_last_hour
  from public.web_login_link_attempts
  where user_id = p_user_id;

  if v_last_min >= 5 or v_last_hour >= 20 then
    return false;
  end if;

  insert into public.web_login_link_attempts (user_id) values (p_user_id);
  return true;
end;
$$;

-- N'autoriser l'appel QUE par le service_role (l'Edge Function).
revoke all on function public.web_login_link_allow(uuid) from public, anon, authenticated;
grant execute on function public.web_login_link_allow(uuid) to service_role;
